In [1]:
import pandas as pd

In [2]:
sessions = pd.read_csv('website_sessions.csv')
pageviews = pd.read_csv('website_pageviews.csv')
orders = pd.read_csv('orders.csv')
order_items = pd.read_csv('order_items.csv')
refunds = pd.read_csv('order_item_refunds.csv')
products = pd.read_csv('products.csv')

<h1 align='center'> Sessions </h1>

In [3]:
sessions.head()

,website_session_id,created_at,user_id,is_repeat_session,utm_source,utm_campaign,utm_content,device_type,http_referer
0,1,2012-03-19 08:04:16,1,0,gsearch,nonbrand,g_ad_1,mobile,https://www.gsearch.com
1,2,2012-03-19 08:16:49,2,0,gsearch,nonbrand,g_ad_1,desktop,https://www.gsearch.com
2,3,2012-03-19 08:26:55,3,0,gsearch,nonbrand,g_ad_1,desktop,https://www.gsearch.com
3,4,2012-03-19 08:37:33,4,0,gsearch,nonbrand,g_ad_1,desktop,https://www.gsearch.com
4,5,2012-03-19 09:00:55,5,0,gsearch,nonbrand,g_ad_1,mobile,https://www.gsearch.com

In [4]:
sessions.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 472871 entries, 0 to 472870
Data columns (total 9 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   website_session_id  472871 non-null  int64
 1   created_at          472871 non-null  object
 2   user_id             472871 non-null  int64
 3   is_repeat_session   472871 non-null  int64
 4   utm_source          389543 non-null  object
 5   utm_campaign        389543 non-null  object
 6   utm_content         389543 non-null  object
 7   device_type         472871 non-null  object
 8   http_referer        432954 non-null  object
dtypes: int64(3), object(6)
memory usage: 32.5+ MB

In [5]:
sessions.isnull().sum().sort_values(ascending=False)

utm_source            83328
utm_content           83328
utm_campaign          83328
http_referer          39917
website_session_id        0
is_repeat_session         0
user_id                   0
created_at                0
device_type               0
dtype: int64

In [6]:
sessions[sessions['user_id'] == 0]

Empty DataFrame
Columns: [website_session_id, created_at, user_id, is_repeat_session, utm_source, utm_campaign, utm_content, device_type, http_referer]
Index: []

1. Handling null values for utm_source

In [7]:
sessions[(sessions['utm_source'].isnull()) & (sessions['http_referer'].isnull() == False)]

,website_session_id,created_at,user_id,is_repeat_session,utm_source,utm_campaign,utm_content,device_type,http_referer
1123,1124,2012-03-26 20:32:17,1120,0,NaN,NaN,NaN,mobile,https://www.gsearch.com
1174,1175,2012-03-27 09:31:58,218,1,NaN,NaN,NaN,mobile,https://www.gsearch.com
1247,1248,2012-03-27 15:32:30,1243,0,NaN,NaN,NaN,desktop,https://www.gsearch.com
1279,1280,2012-03-27 19:28:39,1275,0,NaN,NaN,NaN,desktop,https://www.gsearch.com
1375,1376,2012-03-28 12:27:49,1370,0,NaN,NaN,NaN,mobile,https://www.gsearch.com
...,...,...,...,...,...,...,...,...,...
472825,472826,2015-03-19 05:52:50,394281,0,NaN,NaN,NaN,desktop,https://www.bsearch.com
472827,472828,2015-03-19 05:57:26,363359,1,NaN,NaN,NaN,desktop,https://www.bsearch.com
472835,472836,2015-03-19 06:25:38,394289,0,NaN,NaN,NaN,desktop,https://www.gsearch.com
472846,472847,2015-03-19 06:57:13,378178,1,NaN,NaN,NaN,mobile,https://www.gsearch.com
472863,472864,2015-03-19 07:41:11,394311,0,NaN,NaN,NaN,desktop,https://www.gsearch.com

In [8]:
sessions['utm_source'].unique()

array(['gsearch', nan, 'bsearch', 'socialbook'], dtype=object)

In [9]:
sessions['http_referer'].unique()

array(['https://www.gsearch.com', nan, 'https://www.bsearch.com',
       'https://www.socialbook.com'], dtype=object)

In [10]:
# fill the null values for utm_source based on http refer
def get_source(row):
    if pd.isnull(row['utm_source']):
        if row['http_referer'] == 'https://www.gsearch.com':
            return 'gsearch'
        elif row['http_referer'] == 'https://www.bsearch.com':
            return 'bsearch'
        elif row['http_referer'] == 'https://www.socialbook.com':
            return 'socialbook'
        else:
            return 'direct'
    else:
        return row['utm_source']

sessions['utm_source'] = sessions.apply(get_source,axis=1)

In [11]:
sessions['utm_source'].isnull().sum()

np.int64(0)

In [12]:
sessions['utm_source'].unique()

array(['gsearch', 'direct', 'bsearch', 'socialbook'], dtype=object)

2. Handling null values for campaign
- no other column can recover it, so fill with a label that fits what this column actually represents.
- will replace null with no_campaign_tag

In [13]:
sessions['utm_campaign'].unique()

array(['nonbrand', nan, 'brand', 'pilot', 'desktop_targeted'],
      dtype=object)

In [14]:
sessions['utm_campaign'] = sessions['utm_campaign'].fillna('no_campaign_tag')

3. Handling null values for utm_content
- it identifies the specific ad creative (e.g. g_ad_1 vs g_ad_2), and no other column in this dataset captures that level of detail. So when utm_content is null, there is no way to
recover the real value.
- fill nulls with a clear, self-documenting label ('no_ad_tag')

In [15]:
sessions['utm_content'].unique()

array(['g_ad_1', nan, 'g_ad_2', 'b_ad_2', 'b_ad_1', 'social_ad_1',
       'social_ad_2'], dtype=object)

In [16]:
sessions['utm_content'] = sessions['utm_content'].fillna('no_ad_tag')

4. Handling null values for http referer.
- Will fill the null values as direct which is most widely used as default.
- It indicates traffic came directly witout referer (typed the URL, used a bookmark, or privacy settings stripped the referrer)

In [17]:
sessions['http_referer'] = sessions['http_referer'].fillna('direct')

In [18]:
sessions['http_referer'].unique()

array(['https://www.gsearch.com', 'direct', 'https://www.bsearch.com',
       'https://www.socialbook.com'], dtype=object)

In [19]:
sessions['http_referer'].isnull().sum()

np.int64(0)

In [20]:
sessions.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 472871 entries, 0 to 472870
Data columns (total 9 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   website_session_id  472871 non-null  int64
 1   created_at          472871 non-null  object
 2   user_id             472871 non-null  int64
 3   is_repeat_session   472871 non-null  int64
 4   utm_source          472871 non-null  object
 5   utm_campaign        472871 non-null  object
 6   utm_content         472871 non-null  object
 7   device_type         472871 non-null  object
 8   http_referer        472871 non-null  object
dtypes: int64(3), object(6)
memory usage: 32.5+ MB

In [21]:
cols_to_convert = ['utm_source', 'utm_campaign', 'utm_content',
                    'device_type', 'http_referer']

sessions[cols_to_convert] = sessions[cols_to_convert].astype('string')

sessions.dtypes

website_session_id             int64
created_at                    object
user_id                        int64
is_repeat_session              int64
utm_source            string[python]
utm_campaign          string[python]
utm_content           string[python]
device_type           string[python]
http_referer          string[python]
dtype: object

<h1 align="center"> PageViews </h1>

In [22]:
pageviews.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1188124 entries, 0 to 1188123
Data columns (total 4 columns):
 #   Column               Non-Null Count    Dtype
---  ------               --------------    -----
 0   website_pageview_id  1188124 non-null  int64
 1   created_at           1188124 non-null  object
 2   website_session_id   1188124 non-null  int64
 3   pageview_url         1188124 non-null  object
dtypes: int64(2), object(2)
memory usage: 36.3+ MB

In [23]:
pageviews.head()

   website_pageview_id           created_at  website_session_id pageview_url
0                    1  2012-03-19 08:04:16                   1        /home
1                    2  2012-03-19 08:16:49                   2        /home
2                    3  2012-03-19 08:26:55                   3        /home
3                    4  2012-03-19 08:37:33                   4        /home
4                    5  2012-03-19 09:00:55                   5        /home

In [24]:
pageviews.isnull().sum().sort_values(ascending=False)

website_pageview_id    0
created_at             0
website_session_id     0
pageview_url           0
dtype: int64

In [25]:
pageviews[(pageviews['website_pageview_id'] == 0) | (pageviews['website_session_id'] == 0)]

Empty DataFrame
Columns: [website_pageview_id, created_at, website_session_id, pageview_url]
Index: []

In [26]:
pageviews['pageview_url'].unique()

array(['/home', '/products', '/the-original-mr-fuzzy', '/cart',
       '/shipping', '/billing', '/thank-you-for-your-order', '/lander-1',
       '/billing-2', '/the-forever-love-bear', '/lander-2', '/lander-3',
       '/the-birthday-sugar-panda', '/lander-4', '/lander-5',
       '/the-hudson-river-mini-bear'], dtype=object)

In [27]:
pageviews['pageview_url'].astype('string')

0                           /home
1                           /home
2                           /home
3                           /home
4                           /home
                    ...
1188119                 /shipping
1188120    /the-original-mr-fuzzy
1188121                /billing-2
1188122                     /home
1188123    /the-original-mr-fuzzy
Name: pageview_url, Length: 1188124, dtype: string

<h1 align="center"> Orders </h1>

In [28]:
orders.head()

,order_id,created_at,website_session_id,user_id,primary_product_id,items_purchased,price_usd,cogs_usd
0,1,2012-03-19 10:42:46,20,20,1,1,49.99,19.49
1,2,2012-03-19 19:27:37,104,104,1,1,49.99,19.49
2,3,2012-03-20 06:44:45,147,147,1,1,49.99,19.49
3,4,2012-03-20 09:41:45,160,160,1,1,49.99,19.49
4,5,2012-03-20 11:28:15,177,177,1,1,49.99,19.49

In [29]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32313 entries, 0 to 32312
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            32313 non-null  int64
 1   created_at          32313 non-null  object
 2   website_session_id  32313 non-null  int64
 3   user_id             32313 non-null  int64
 4   primary_product_id  32313 non-null  int64
 5   items_purchased     32313 non-null  int64
 6   price_usd           32313 non-null  float64
 7   cogs_usd            32313 non-null  float64
dtypes: float64(2), int64(5), object(1)
memory usage: 2.0+ MB

In [30]:
orders[orders['primary_product_id']==0]

Empty DataFrame
Columns: [order_id, created_at, website_session_id, user_id, primary_product_id, items_purchased, price_usd, cogs_usd]
Index: []

In [31]:
orders[orders['items_purchased']==0]

Empty DataFrame
Columns: [order_id, created_at, website_session_id, user_id, primary_product_id, items_purchased, price_usd, cogs_usd]
Index: []

<h1 align="center"> Orders Items </h1>

In [32]:
order_items.head()

,order_item_id,created_at,order_id,product_id,is_primary_item,price_usd,cogs_usd
0,1,2012-03-19 10:42:46,1,1,1,49.99,19.49
1,2,2012-03-19 19:27:37,2,1,1,49.99,19.49
2,3,2012-03-20 06:44:45,3,1,1,49.99,19.49
3,4,2012-03-20 09:41:45,4,1,1,49.99,19.49
4,5,2012-03-20 11:28:15,5,1,1,49.99,19.49

In [33]:
order_items.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40025 entries, 0 to 40024
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   order_item_id    40025 non-null  int64
 1   created_at       40025 non-null  object
 2   order_id         40025 non-null  int64
 3   product_id       40025 non-null  int64
 4   is_primary_item  40025 non-null  int64
 5   price_usd        40025 non-null  float64
 6   cogs_usd         40025 non-null  float64
dtypes: float64(2), int64(4), object(1)
memory usage: 2.1+ MB

In [34]:
order_items['is_primary_item'].unique()

array([1, 0])

<h1 align="center"> Refunds </h1>

In [35]:
refunds.head()

,order_item_refund_id,created_at,order_item_id,order_id,refund_amount_usd
0,1,2012-04-06 11:32:43,57,57,49.99
1,2,2012-04-13 01:09:43,74,74,49.99
2,3,2012-04-15 07:03:48,71,71,49.99
3,4,2012-04-17 20:00:37,118,118,49.99
4,5,2012-04-22 20:53:49,116,116,49.99

In [36]:
refunds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1731 entries, 0 to 1730
Data columns (total 5 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   order_item_refund_id  1731 non-null   int64
 1   created_at            1731 non-null   object
 2   order_item_id         1731 non-null   int64
 3   order_id              1731 non-null   int64
 4   refund_amount_usd     1731 non-null   float64
dtypes: float64(1), int64(3), object(1)
memory usage: 67.7+ KB

<h1 align="center"> Products </h1>

In [37]:
products

   product_id           created_at                product_name
0           1  2012-03-19 08:00:00      The Original Mr. Fuzzy
1           2  2013-01-06 13:00:00       The Forever Love Bear
2           3  2013-12-12 09:00:00    The Birthday Sugar Panda
3           4  2014-02-05 10:00:00  The Hudson River Mini bear

<h1 align="center"> Convert to DB </h1>

In [38]:
sessions['created_at'] = pd.to_datetime(sessions['created_at'])
pageviews['created_at'] = pd.to_datetime(pageviews['created_at'])
orders['created_at'] = pd.to_datetime(orders['created_at'])
products['created_at'] = pd.to_datetime(sessions['created_at'])
refunds['created_at'] = pd.to_datetime(pageviews['created_at'])
order_items['created_at'] = pd.to_datetime(orders['created_at'])

In [ ]:
from sqlalchemy import create_engine

# format: mysql+pymysql://username:password@host:port/schema_name
engine = create_engine('mysql+pymysql://user:***@localhost:3306/toy_store')

sessions.to_sql('website_sessions', engine, if_exists='replace', index=False,method='multi',chunksize=1000)
pageviews.to_sql('website_pageviews', engine, if_exists='replace', index=False,method='multi',chunksize=1000)
orders.to_sql('orders', engine, if_exists='replace', index=False,method='multi',chunksize=1000)
order_items.to_sql('order_items', engine, if_exists='replace', index=False,method='multi',chunksize=1000)
refunds.to_sql('order_item_refunds', engine, if_exists='replace', index=False,method='multi',chunksize=1000)
products.to_sql('products', engine, if_exists='replace', index=False,method='multi',chunksize=1000)

print("All tables loaded successfully")

All tables loaded successfully

<h1 align="center"> EDA </h1>

In [40]:
pageviews.groupby('pageview_url').count()

,website_pageview_id,created_at,website_session_id
pageview_url,,,
/billing,3617,3617,3617
/billing-2,48441,48441,48441
/cart,94953,94953,94953
/home,137576,137576,137576
/lander-1,47574,47574,47574
/lander-2,131170,131170,131170
/lander-3,79000,79000,79000
/lander-4,9385,9385,9385
/lander-5,68166,68166,68166
/products,261231,261231,261231
/shipping,64484,64484,64484
/thank-you-for-your-order,32313,32313,32313
/the-birthday-sugar-panda,19046,19046,19046
/the-forever-love-bear,26033,26033,26033
/the-hudson-river-mini-bear,2610,2610,2610
/the-original-mr-fuzzy,162525,162525,162525

In [41]:
page_sessions = pageviews.join(sessions,on="website_session_id",how="left",lsuffix="p")
page_sessions.head(5)

,website_pageview_id,created_atp,website_session_idp,pageview_url,website_session_id,created_at,user_id,is_repeat_session,utm_source,utm_campaign,utm_content,device_type,http_referer
0,1,2012-03-19 08:04:16,1,/home,2.0,2012-03-19 08:16:49,2.0,0.0,gsearch,nonbrand,g_ad_1,desktop,https://www.gsearch.com
1,2,2012-03-19 08:16:49,2,/home,3.0,2012-03-19 08:26:55,3.0,0.0,gsearch,nonbrand,g_ad_1,desktop,https://www.gsearch.com
2,3,2012-03-19 08:26:55,3,/home,4.0,2012-03-19 08:37:33,4.0,0.0,gsearch,nonbrand,g_ad_1,desktop,https://www.gsearch.com
3,4,2012-03-19 08:37:33,4,/home,5.0,2012-03-19 09:00:55,5.0,0.0,gsearch,nonbrand,g_ad_1,mobile,https://www.gsearch.com
4,5,2012-03-19 09:00:55,5,/home,6.0,2012-03-19 09:05:46,6.0,0.0,gsearch,nonbrand,g_ad_1,desktop,https://www.gsearch.com

In [42]:
page_sessions.groupby('pageview_url')['user_id'].nunique()

pageview_url
/billing                         3580
/billing-2                      47161
/cart                           90407
/home                          128076
/lander-1                       43235
/lander-2                      119346
/lander-3                       74822
/lander-4                        9107
/lander-5                       62048
/products                      232068
/shipping                       62368
/thank-you-for-your-order       31731
/the-birthday-sugar-panda       18739
/the-forever-love-bear          25615
/the-hudson-river-mini-bear      2598
/the-original-mr-fuzzy         150403
Name: user_id, dtype: int64

In [43]:
order_items.groupby('product_id')['order_id'].nunique()

product_id
1    24226
2     5796
3     4985
4     5018
Name: order_id, dtype: int64